[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    { key = "Return",   mods = "Control | Shift", action = "ToggleFullscreen" }, # For Windows
    { key = "Return",   mods = "Command | Shift", action = "ToggleFullscreen" }, # For Mac
    { key = "PageUp",   mods = "Control",         action = "ScrollHalfPageUp" },
    { key = "PageDown", mods = "Control",         action = "ScrollHalfPageDown" },
    { key = "N",        mods = "Control | Shift", action = "CreateNewWindow" },
]

[font]
size = 12.0
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

[window]
padding = { x = 1, y = 1 }
dynamic_padding = true

# Colors (Horizon Dark)

# Primary colors
[colors.primary]
background = '#1c1e26'
foreground = '#e0e0e0'

# Normal colors
[colors.normal]
black = '#16161c'
red = '#e95678'
green = '#29d398'
yellow = '#fab795'
blue = '#26bbd9'
magenta = '#ee64ac'
cyan = '#59e1e3'
white = '#d5d8da'

# Bright colors
[colors.bright]
black = '#5b5858'
red = '#ec6a88'
green = '#3fdaa4'
yellow = '#fbc3a7'
blue = '#3fc4de'
magenta = '#f075b5'
cyan = '#6be4e6'
white = '#d5d8da'
