vim.keymap.set("n", "<leader>f", ":GFiles<CR>", { desc = "[S]earch [F]iles" })
vim.keymap.set("n", "<leader>F", ":Files<CR>", { desc = "[S]earch [H]elp" })
vim.keymap.set("n", "<leader>t", ":BTags<CR>", { desc = "[S]earch current [W]ord" })
vim.keymap.set("n", "<leader>T", ":Tags<CR>", { desc = "[S]earch by [G]rep on Git Root" })
vim.keymap.set("n", "<leader>b", ":Buffers<CR>", { desc = "[S]earch [D]iagnostics" })
vim.keymap.set("n", "<leader>c", ":BCommits<CR>", { desc = "[S]earch [D]iagnostics" })
vim.keymap.set("n", "<leader>C", ":Commits<CR>", { desc = "[S]earch [D]iagnostics" })
vim.keymap.set("n", "<leader>/", ":Rg<CR>", { desc = "[S]earch by [G]rep" })
