vim.keymap.set("n", "<leader>g", ":GFiles<CR>", { desc = "Fzf for [g]it files" })
vim.keymap.set("n", "<leader>f", ":Files<CR>", { desc = "Fzf for [f]iles" })
vim.keymap.set("n", "<leader>t", ":BTags<CR>", { desc = "Fzf for tags in current buffer" })
vim.keymap.set("n", "<leader>T", ":Tags<CR>", { desc = "Fzf for tags in directory" })
vim.keymap.set("n", "<leader>b", ":Buffers<CR>", { desc = "Fzf for open buffers" })
vim.keymap.set("n", "<leader>c", ":BCommits<CR>", { desc = "Fzf commits made in this file" })
vim.keymap.set("n", "<leader>C", ":Commits<CR>", { desc = "Fzf all commits" })
vim.keymap.set("n", "<leader>/", ":Rg<CR>", { desc = "Fzf for patten in file" })
